

[package]
name = "blog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.35.0", features = ["full"] }
warp = "0.3.6"
pulldown-cmark = "0.9.3"
bytes = "1.5.0"
